language: python
python: 2.7
sudo: false
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
  - PLONE_VERSION=5.0 QA=true
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.0
    - python: 2.6
      env: PLONE_VERSION=4.1
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then echo 'plone.recipe.codeanalysis = 1.1' >> travis.cfg; fi
  - mkdir -p buildout-cache/downloads
  - if [[ $PLONE_VERSION == 4.* ]]; then python bootstrap.py -c travis.cfg; else python bootstrap-buildout.py -c travis.cfg; fi 
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script: bin/code-analysis && bin/test
after_success:
  - test $QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
